spring.application.name=Carri-Okay-Backend
spring.datasource.url=jdbc:mysql://localhost:3306/carriokay2
spring.datasource.username=root
spring.datasource.password=3945

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=2400031412cse1@gmail.com
spring.mail.password=tcog mrbx ijar bwnd

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
